settings:
  # if true, you will get teleported to the lobby upon joining
  # if false, you won't get teleported to the lobby upon joining
  teleport: true

  # A block of your choice, it also accepts data values
  # This is the block the players will be placing while practicing
  # block: WOOL:14 = RED WOOL
  block: WOOL

  leaderboard:
    # the leaderboard size
    size: 10

    format:
      # the message header
      header: "&eLeaderboard"

      # the message style
      style: "&e{position}. {name} &a({score})"


mode:
  default: hard
  list:
    standard: 0-10
    hard: 11-20